[phases.setup]
nixPkgs = ['nodejs-20_x', 'pnpm']

[phases.install]
cmds = [
  'pnpm config set store-dir ~/.pnpm-store',
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = [
  'pnpm prisma generate',
  'pnpm build'
]

[start]
cmd = 'pnpm start:prod'
